# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assignment6.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 80, 91, 41))
        self.label.setObjectName("label")
        self.l1 = QtWidgets.QLineEdit(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(220, 80, 181, 31))
        self.l1.setInputMask("")
        self.l1.setObjectName("l1")
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(430, 80, 93, 28))
        self.b1.setObjectName("b1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 160, 55, 16))
        self.label_2.setObjectName("label_2")
        self.l2 = QtWidgets.QLineEdit(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(260, 160, 113, 22))
        self.l2.setObjectName("l2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 240, 55, 16))
        self.label_3.setObjectName("label_3")
        self.l3 = QtWidgets.QLineEdit(self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(210, 240, 191, 31))
        self.l3.setObjectName("l3")
        self.b2 = QtWidgets.QPushButton(self.centralwidget)
        self.b2.setGeometry(QtCore.QRect(420, 240, 93, 28))
        self.b2.setObjectName("b2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 330, 55, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(270, 330, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.b1.clicked.connect(self.button_)
        self.b2.clicked.connect(self.total_)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Book Title"))
        self.l1.setText(_translate("MainWindow", "text"))
        self.b1.setText(_translate("MainWindow", "Find Price"))
        self.label_2.setText(_translate("MainWindow", "Price:"))
        self.l2.setText(_translate("MainWindow", "Rs. 0"))
        self.label_3.setText(_translate("MainWindow", "Quantity"))
        self.b2.setText(_translate("MainWindow", "Find Total"))
        self.label_4.setText(_translate("MainWindow", "Total:"))
        self.lineEdit.setText(_translate("MainWindow", "Rs. 0"))
        
    def total_(self):
        #print("Clicked2")
        b=float(self.l2.text()[3:])
        print(type(b))
        q=int(self.l3.text())
        print(type(q))
        tot=b*q
        print(tot)
        #print("check")
        self.lineEdit.setText(str(tot))
        #print("finished")
    def button_(self):
        print("Clicked1")
        bprice=self.findprice(self.l1.text())
        print(bprice)

        if bprice !=0:
            self.l2.setText("Rs."+str(bprice))
        else:
            self.l2.setText("No data")
    def findprice(self,title):
        #getting the data
        try:
           sql='select title,price from books'
           my=sqlite3.connect('bishal.db')
           cur=my.cursor()
           cur.execute(sql)
           store=cur.fetchall()
           d=dict()
           for i in store:
                d[i[0]]=i[1]
           if title in d.keys():
                return d[title]
           else:
               return 0
        except:
            print("Exception occured")
            return ""
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    #ui.myfunction() 
    sys.exit(app.exec_())







